/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.tillias.spbka.schema.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Avro Schema for Event */
@org.apache.avro.specific.AvroGenerated
public class Event2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1633466607428587314L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Event2\",\"namespace\":\"com.github.tillias.spbka.schema.avro\",\"doc\":\"Avro Schema for Event\",\"fields\":[{\"name\":\"n1\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Event2> ENCODER =
      new BinaryMessageEncoder<Event2>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Event2> DECODER =
      new BinaryMessageDecoder<Event2>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Event2> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Event2> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Event2> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Event2>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Event2 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Event2 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Event2 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Event2 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence n1;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Event2() {}

  /**
   * All-args constructor.
   * @param n1 The new value for n1
   */
  public Event2(java.lang.CharSequence n1) {
    this.n1 = n1;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return n1;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: n1 = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'n1' field.
   * @return The value of the 'n1' field.
   */
  public java.lang.CharSequence getN1() {
    return n1;
  }


  /**
   * Sets the value of the 'n1' field.
   * @param value the value to set.
   */
  public void setN1(java.lang.CharSequence value) {
    this.n1 = value;
  }

  /**
   * Creates a new Event2 RecordBuilder.
   * @return A new Event2 RecordBuilder
   */
  public static com.github.tillias.spbka.schema.avro.Event2.Builder newBuilder() {
    return new com.github.tillias.spbka.schema.avro.Event2.Builder();
  }

  /**
   * Creates a new Event2 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Event2 RecordBuilder
   */
  public static com.github.tillias.spbka.schema.avro.Event2.Builder newBuilder(com.github.tillias.spbka.schema.avro.Event2.Builder other) {
    if (other == null) {
      return new com.github.tillias.spbka.schema.avro.Event2.Builder();
    } else {
      return new com.github.tillias.spbka.schema.avro.Event2.Builder(other);
    }
  }

  /**
   * Creates a new Event2 RecordBuilder by copying an existing Event2 instance.
   * @param other The existing instance to copy.
   * @return A new Event2 RecordBuilder
   */
  public static com.github.tillias.spbka.schema.avro.Event2.Builder newBuilder(com.github.tillias.spbka.schema.avro.Event2 other) {
    if (other == null) {
      return new com.github.tillias.spbka.schema.avro.Event2.Builder();
    } else {
      return new com.github.tillias.spbka.schema.avro.Event2.Builder(other);
    }
  }

  /**
   * RecordBuilder for Event2 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Event2>
    implements org.apache.avro.data.RecordBuilder<Event2> {

    private java.lang.CharSequence n1;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.tillias.spbka.schema.avro.Event2.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.n1)) {
        this.n1 = data().deepCopy(fields()[0].schema(), other.n1);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Event2 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.tillias.spbka.schema.avro.Event2 other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.n1)) {
        this.n1 = data().deepCopy(fields()[0].schema(), other.n1);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'n1' field.
      * @return The value.
      */
    public java.lang.CharSequence getN1() {
      return n1;
    }


    /**
      * Sets the value of the 'n1' field.
      * @param value The value of 'n1'.
      * @return This builder.
      */
    public com.github.tillias.spbka.schema.avro.Event2.Builder setN1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.n1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'n1' field has been set.
      * @return True if the 'n1' field has been set, false otherwise.
      */
    public boolean hasN1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'n1' field.
      * @return This builder.
      */
    public com.github.tillias.spbka.schema.avro.Event2.Builder clearN1() {
      n1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Event2 build() {
      try {
        Event2 record = new Event2();
        record.n1 = fieldSetFlags()[0] ? this.n1 : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Event2>
    WRITER$ = (org.apache.avro.io.DatumWriter<Event2>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Event2>
    READER$ = (org.apache.avro.io.DatumReader<Event2>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.n1);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.n1 = in.readString(this.n1 instanceof Utf8 ? (Utf8)this.n1 : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.n1 = in.readString(this.n1 instanceof Utf8 ? (Utf8)this.n1 : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










