server:
  port: 8080
spring:
  kafka:
    consumer:
      bootstrap-servers: vm-minikube:30092,vm-minikube:30093,vm-minikube:30094
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
      properties:
        spring.json.trusted.packages: "com.github.tillias.spbka"
        apicurio:
          registry:
            use-specific-avro-reader: true
            url: http://vm-minikube:30109/api
    producer:
      bootstrap-servers: vm-minikube:30092,vm-minikube:30093,vm-minikube:30094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
      properties:
        apicurio:
          registry:
            url: http://vm-minikube:30109/api
            artifact-id: io.apicurio.registry.utils.serde.strategy.TopicIdStrategy